"""Write a cover letter draft to drafts/ for one posting. Never sends anything."""
import json
import pathlib
import re

from copilot.descriptions import fetch_description, supports
from copilot.llm import draft_cover_letter, get_client
from copilot.scoring import RESUME_PATH

DRAFTS_DIR = pathlib.Path("drafts")

# A posting plus its score row, looked up by the short id shown in `report`.
SELECT_ONE_SQL = """SELECT p.*, s.score, s.emphasize
FROM postings p
LEFT JOIN scores s ON s.source = p.source AND s.source_id = p.source_id
WHERE p.source_id LIKE ?"""

HEADER = """<!-- UNREVIEWED DRAFT - generated by copilot, not checked by a human.
Edit it, verify every claim against your resume, then send it yourself. -->

"""


def _slug(text: str) -> str:
    """Filesystem-safe lowercase name: 'Apex Technology, Inc.' -> 'apex-technology-inc'."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def draft(conn, id_prefix: str, force: bool = False) -> None:
    rows = conn.execute(SELECT_ONE_SQL, (f"{id_prefix}%",)).fetchall()
    # YOU (1): guard the two bad cases before spending an API call -
    # no match, and more than one match (the Kudu problem). Print and return.
    if len(rows) == 0:
        print(f"No matching posting found for ID prefix: {id_prefix}")
        return
    if len(rows) > 1:
        print(f"Multiple matching postings found for ID prefix: {id_prefix}")
        return

    posting = rows[0]

    # Refuse before spending anything: an edited draft is the only copy of your work.
    DRAFTS_DIR.mkdir(exist_ok=True)
    path = DRAFTS_DIR / f"{_slug(posting['company'])}-{posting['source_id'][:8]}.md"
    if path.exists() and not force:
        print(f"{path} already exists - your edits stay put.")
        print("Pass --force to overwrite it, or delete the file first.")
        return

    resume = RESUME_PATH.read_text(encoding="utf-8")
    emphasize = json.loads(posting['emphasize']) if posting['emphasize'] else []

    description = posting["description"] or fetch_description(posting["url"])
    if description:
        print(f"Fetched the employer's description ({len(description)} chars) - "
              "the draft will include a grounded 'why this role' paragraph.")
    elif supports(posting["url"]):
        print("No description: the employer's board no longer lists this job, so it may "
              "be closed. Verify before applying. Skipping the 'why this role' paragraph.")
    else:
        print(f"No description available for {posting['url']} (not a source we can query). "
              "Skipping the 'why this role' paragraph - add it yourself after reading the posting.")

    letter = draft_cover_letter(get_client(), resume, posting, emphasize, description)

    path.write_text(HEADER + letter, encoding="utf-8")
    print(f"Draft cover letter written to: {path}")
